local black = "#000000" -- black
local black1 = "#212121" -- Eries Black
local gray = "#5b5b5b" -- Davys Grey
local white = "#dfd4cc" -- Timberworlf
local primary1 = "#89a479" -- Asparagus
local primary2 = "#80874c" -- moos Green

local colors = {
    black=black,
    black1=black1,
    white=white,
    primary1=primary1,
    primary2=primary2,
    fg = white,
    bg = black,
    alt_fg = white,
    alt_bg = black1,
    line = gray,
    dark_gray = gray,
    gray = gray,
    context = gray,
    light_gray = white,
    red = primary2,
    blue = white,
    green = primary2,
    cyan = primary1,
    orange = primary1,
    yellow = primary1,
    purple = primary1,
    magenta = primary1,
    cursor_fg = white,
    cursor_bg = white,
    sign_add = primary1,
    sign_change = primary1,
    sign_delete = primary2,
    sign_add_alt = primary1,
    sign_change_alt = primary1,
    error = primary2,
    warn = primary2,
    info = primary2,
    hint = primary2,
    error_bg = black1,
    warn_bg = black1,
    info_bg = black1,
    hint_bg = black1,
    reference = black1,
    success_green = primary1,
    folder_blue = primary2,
    ui_blue = gray,
    ui2_blue = gray,
    ui3_blue = gray,
    ui4_blue = gray,
    ui5_blue = gray,
    ui_orange = gray,
    ui2_orange = gray,
    ui_purple = gray,
}

return colors
