local c = require "minimal.palette"

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()
    -- Editor
    hl(0, "Normal", { fg = c.white, bg = c.black })
    hl(0, "SignColumn", { fg = c.light, bg = c.black })
    hl(0, "MsgArea", { fg = c.white, bg = c.black })
    hl(0, "ModeMsg", { fg = c.white, bg = c.dark })
    hl(0, "MsgSeparator", { fg = c.white, bg = c.black })
    hl(0, "SpellBad", { fg = "NONE", bg = "NONE", sp = c.primary, undercurl = true })
    hl(0, "SpellCap", { fg = "NONE", bg = "NONE", sp = c.yellow, undercurl = true })
    hl(0, "SpellLocal", { fg = "NONE", bg = "NONE", sp = c.green, underline = true })
    hl(0, "SpellRare", { fg = "NONE", bg = "NONE", sp = c.purple, underline = true })
    hl(0, "NormalNC", { fg = c.white, bg = c.black })
    hl(0, "Pmenu", { fg = c.silver, bg = c.dark })
    hl(0, "PmenuSel", { fg = "NONE", bg = c.dark })
    hl(0, "WildMenu", { fg = c.white, bg = c.dark })
    hl(0, "CursorLineNr", { fg = c.white, bg = "NONE", bold = true })
    hl(0, "Folded", { fg = c.light, bg = c.gray })
    hl(0, "FoldColumn", { fg = c.gray, bg = c.dark })
    hl(0, "LineNr", { fg = c.silver, bg = "NONE" })
    hl(0, "FloatBoder", { fg = c.gray, bg = c.dark })
    hl(0, "Whitespace", { fg = c.black, bg = "NONE" })
    hl(0, "VertSplit", { fg = c.dark, bg = c.black })
    hl(0, "CursorLine", { fg = "NONE", bg = c.dark })
    hl(0, "CursorColumn", { fg = "NONE", bg = c.dark })
    hl(0, "ColorColumn", { fg = "NONE", bg = c.dark })
    hl(0, "NormalFloat", { fg = "NONE", bg = c.alt_bg })
    hl(0, "Visual", { fg = "NONE", bg = c.dark })
    hl(0, "VisualNOS", { fg = "NONE", bg = c.dark })
    hl(0, "WarningMsg", { fg = c.secondary, bg = c.black })
    hl(0, "DiffText", { fg = c.dark, bg = c.gray })
    hl(0, "DiffAdd", { fg = c.alt_bg, bg = c.sign_add })
    hl(0, "DiffChange", { fg = c.alt_bg, bg = c.sign_change, underline = true })
    hl(0, "DiffDelete", { fg = c.alt_bg, bg = c.sign_delete })
    hl(0, "QuickFixLine", { fg = "NONE", bg = c.ui2_blue })
    hl(0, "PmenuSbar", { fg = "NONE", bg = c.alt_bg })
    hl(0, "PmenuThumb", { fg = "NONE", bg = c.gray })
    hl(0, "MatchWord", { fg = "NONE", bg = c.gray })
    hl(0, "MatchParen", { fg = c.hint, bg = c.gray })
    hl(0, "MatchWordCur", { fg = "NONE", bg = c.gray })
    hl(0, "MatchParenCur", { fg = "NONE", bg = c.gray })
    hl(0, "Cursor", { fg = c.white, bg = c.white })
    hl(0, "lCursor", { fg = c.white, bg = c.white })
    hl(0, "CursorIM", { fg = c.white, bg = c.white })
    hl(0, "TermCursor", { fg = c.white, bg = c.white })
    hl(0, "TermCursorNC", { fg = c.white, bg = c.white })
    hl(0, "Conceal", { fg = c.gray, bg = "NONE" })
    hl(0, "Directory", { fg = c.primary, bg = "NONE" })
    hl(0, "SpecialKey", { fg = c.primary, bg = "NONE", bold = true })
    hl(0, "ErrorMsg", { fg = c.secondary, bg = c.bg, bold = true })
    hl(0, "Search", { fg = "NONE", bg = c.gray })
    hl(0, "IncSearch", { fg = "NONE", bg = c.gray })
    hl(0, "Substitute", { fg = "NONE", bg = c.gray })
    hl(0, "MoreMsg", { fg = c.secondary, bg = "NONE" })
    hl(0, "Question", { fg = c.secondary, bg = "NONE" })
    hl(0, "EndOfBuffer", { fg = c.black, bg = "NONE" })
    hl(0, "NonText", { fg = c.black, bg = "NONE" })
    hl(0, "TabLine", { fg = c.light_gray, bg = c.line })
    hl(0, "TabLineSel", { fg = c.white, bg = c.gray })
    hl(0, "TabLineFill", { fg = c.gray, bg = c.gray })

    -- Code
    hl(0, "Comment", { fg = c.gray, bg = "NONE" })
    hl(0, "Variable", { fg = c.white, bg = "NONE" })
    hl(0, "String", { fg = c.secondary, bg = "NONE" })
    hl(0, "Character", { fg = c.secondary, bg = "NONE" })
    hl(0, "Number", { fg = c.white, bg = "NONE" })
    hl(0, "Float", { fg = c.white, bg = "NONE" })
    hl(0, "Boolean", { fg = c.white, bg = "NONE" })
    hl(0, "Constant", { fg = c.white, bg = "NONE" })
    hl(0, "Type", { fg = c.primary, bg = "NONE" })
    hl(0, "Function", { fg = c.white, bg = "NONE" })
    hl(0, "Keyword", { fg = c.primary, bg = "NONE" })
    hl(0, "Conditional", { fg = c.primary, bg = "NONE" })
    hl(0, "Repeat", { fg = c.primary, bg = "NONE" })
    hl(0, "Operator", { fg = c.white, bg = "NONE" })
    hl(0, "PreProc", { fg = c.primary, bg = "NONE" })
    hl(0, "Include", { fg = c.primary, bg = "NONE" })
    hl(0, "Exception", { fg = c.secondary, bg = "NONE" })
    hl(0, "StorageClass", { fg = c.primary, bg = "NONE" })
    hl(0, "Structure", { fg = c.primary, bg = "NONE" })
    hl(0, "Typedef", { fg = c.primary, bg = "NONE" })
    hl(0, "Define", { fg = c.primary, bg = "NONE" })
    hl(0, "Macro", { fg = c.primary, bg = "NONE" })
    hl(0, "Debug", { fg = c.secondary, bg = "NONE" })
    hl(0, "Title", { fg = c.primary, bg = "NONE", bold = true })
    hl(0, "Label", { fg = c.white, bg = "NONE" })
    hl(0, "SpecialChar", { fg = c.secondary, bg = "NONE" })
    hl(0, "Delimiter", { fg = c.light, bg = "NONE" })
    hl(0, "SpecialComment", { fg = c.silver, bg = "NONE" })
    hl(0, "Tag", { fg = c.primary, bg = "NONE" })
    hl(0, "Bold", { fg = "NONE", bg = "NONE", bold = true })
    hl(0, "Italic", { fg = "NONE", bg = "NONE", italic = true })
    hl(0, "Underlined", { fg = "NONE", bg = "NONE", underline = true })
    hl(0, "Ignore", { fg = c.gray, bg = "NONE", bold = true })
    hl(0, "Todo", { fg = c.silver, bg = "NONE", bold = true })
    hl(0, "Error", { fg = c.secondary, bg = "NONE", bold = true })
    hl(0, "Statement", { fg = c.primary, bg = "NONE" })
    hl(0, "Identifier", { fg = c.white, bg = "NONE" })
    hl(0, "PreCondit", { fg = c.primary, bg = "NONE" })
    hl(0, "Special", { fg = c.primary, bg = "NONE" })
end

return theme
